### ISSUE TITLE
Feature: Subscribe to devy development

### ISSUE THREAD

**Issue by adavila0703** [adavila0703/devy#51]
In order to not flood users with notifications from the devy development channels, the channels can now only be accessed by people with the "devy developer" role. Have a way we can allow people to subscribe to devy development.

How it would work:
- We have a channel with instructions on how to subscribe.
- The bot gives them the roll to allow them to see the channels on discord
- Then the bot sends them an invite to be a collaborator on the repo.
- Maybe if they are inactive in the repo for a certain amount of time then they are removed.

**Comment by DillonStreator** [comment]
Check if user has role to toggle the role when command is run
https://discord.com/channels/118456055842734083/155361364909621248/565596468879163407
